# Generated by Django 3.1.2 on 2020-11-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.ImageField(upload_to='listings_image'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='imageURL',
            field=models.URLField(max_length=20000),
        ),
    ]
