# Generated by Django 3.1.2 on 2020-11-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201106_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_user',
            field=models.ManyToManyField(blank=True, related_name='active_user', to='auctions.Listings'),
        ),
    ]
