# Generated by Django 3.1.2 on 2020-11-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_active_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image',
        ),
    ]
