# Generated by Django 3.1.2 on 2020-11-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='content',
        ),
    ]
